### ISSUE TITLE
[BABEL] Note: The code generator has deoptimised the styling of D:\Nodejs\next.js-canary\examples\with-tailwindcss\node_modules\react-dom\cjs\react-dom.development.js as it exceeds the max of 500KB.

### ISSUE THREAD

**Issue by IRediTOTO** [Mistereo/next-linaria#1]
Nothing special, just run example of Nextjs and get this warning babel. 
`[BABEL] Note: The code generator has deoptimised the styling of D:\Nodejs\next.js-canary\examples\with-tailwindcss\node_modules\react-dom\cjs\react-dom.development.js as it exceeds the max of 500KB.`

If I remove next-linaria from next.config.js, everything will be ok.

**Comment by Mistereo** [comment]
I think excluding `node_modules` from linaria loader should fix this.

**Comment by Mistereo** [comment]
I've published a fix under `next-linaria@0.10.0`.

**Comment by IRediTOTO** [comment]
Greate, it look faster, thank you so much

**Comment by IRediTOTO** [comment]
@Mistereo  I have this error, Im not sure it come from next-linaria but 90% I think. I tried to my other  project, it have bigger size but no error. 
I use linaria with twin.macro. 
```
<div
      key={index}
        className={css`  ${tw`w-2/3`} `}>
                              <NewsFullThumb post={post} />
                           </div>
```
![image](https://user-images.githubusercontent.com/15695252/95827812-6bb45780-0d5e-11eb-9743-47d0264d348f.png)

**Comment by Mistereo** [comment]
Hard to say anything from this screenshot, can you provide a minimal repro?

**Comment by chirag04** [comment]
Do you even need twin.macro anymore?

```
const button = css`
  text-transform: uppercase;
  @apply px-4;
`;
```

After spending few hours trying to get tailwind, linaria and next.js to work together, i landed on this module and everything worked great!! Thank you so much @Mistereo.
